### ISSUE TITLE
Connection bug - disconnect to connect

### ISSUE THREAD

**Issue by morganhvidt** [msvisser/AnnePro-mac#1]
I clicked disconnect (in the Bluetooth settings) while the app was stuck on try to find the Anne. It didn't disconnect but instead caused the the app to find and connect. Your app is super useful so far! Thanks for developing this!

**Comment by msvisser** [comment]
Thanks for your tip. It does not seem to work reliably for me though. Sometimes disconnecting will let the app see the keyboard, but most of the time it does not work for me. For me just hitting the '+' while in the bluetooth mode on the keyboard works after a lot of tries.

**Comment by msvisser** [comment]
This should be fixed by #3.
