### ISSUE TITLE
Join efforts for an Electron app?

### ISSUE THREAD

**Issue by fcoury** [msvisser/AnnePro-mac#2]
I was about to start writing an Electron app for the Anne Pro using the [noble](https://github.com/sandeepmistry/noble) library and React. 

Would you be interested in joining efforts?

**Comment by msvisser** [comment]
Although it would love to see a cross-platform app for the keyboard, I personally dislike Electron and Node.js, so I probably won't directly help with your app.

But, if you need any help with the communication protocol of the keyboard send me a messages and I would be happy to help. You can find me in the AnnePro dev discord server using the same username.

**Comment by fcoury** [comment]
Thanks!
