### ISSUE TITLE
How Does one Set Custom Layout?

### ISSUE THREAD

**Issue by klaus385** [msvisser/AnnePro-mac#4]
I really just want like Mac Layout + Arrow Layout. Particularly because I dont use the RALT, ANNE, or RCNTRL. But, if you can elaborate further in a README.md that would be great! SO far though the app for lighting and layout settings otherwise has been great.

**Comment by msvisser** [comment]
In the layout menu you can click the custom layout option, this should open up the layout settings window like shown in the screenshots. In this window you can load one of the default layouts with the three buttons, and you can upload and download your custom layout to/from your keyboard. You can pick different keys using the drop-down menus and create a custom layout. You are required to have the FN and ANNE key in your layout. To get command and option use win and alt respectively. I will try to put this information in the README too. If you have any more questions, just leave another comment.
