### ISSUE TITLE
[Feature] Export and import custom lighting layout

### ISSUE THREAD

**Issue by danielbertolozi** [msvisser/AnnePro-mac#7]
Just an idea, to be able to import and export lighting layouts.

I'm not proficient in Swift in any ways (although I know the syntax), but I am willing to help in all ways possible.

**Comment by danielbertolozi** [comment]
Also: perhaps doing it in some way (JSON?) that it is possible to import and export between various apps (e.g. a Windows client)?

**Comment by lo-bertolino** [comment]
Hey, I'm trying to make exporting and importing work, I'm not even aware of similar features on other apps and I can barely understand the way data is saved to the keyboard and in the app so I don't think I'll be able to make it compatible with other clients, I'm going to export in JSON tough but it won't improve much the readability or compatibility
If I can make it work, I'll try to also make an import/export thing for the layouts

**Comment by msvisser** [comment]
Implemented by #8
